### ISSUE TITLE
Low compatibility with windows, safari, etc.

### ISSUE THREAD

**Issue by peterdaly13** [piedras77/centralized_smart_dashboard#20]
We understand that this might not be an issue as your client has requested the app to be built for linux/chrome, but in our testing process, there were many hurdles in our efforts to simply get the program running when using Windows machines. Additionally, there are some UI issues when attempting to access the app using Safari.

Severity: Low

**Comment by WillDaru22** [comment]
ROS is a unix based tool and so there are some unavoidable conflicts with non-unix based systems.

**Comment by piedras77** [comment]
Yes, this issue is analogous to saying an android app cannot be run in iOS. In a different development cycle, one might make an android app hybrid or straight out a new iOS app. Similarly, this backend application is meant to run in Unix, not in Windows. In particular, for the reason mentioned by @WillDaru22
